### ISSUE TITLE
RPNv2 setup

### ISSUE THREAD

**Issue by meyskens** [src-d/terraform-provider-online-net#6]
We should verify that the module currently is able to configure the RPNv2 setup correctly.
Currently the code seems to refer to `RPN` which is different than `RPNv2`, if it is actually v2 I propose to rename it to be clear since they seem to keep co-existing.

What we need for our use is
* RPNv2 group resource
* Adding/removing RPNv2 membership
* Setting VLAN ID of the membership

**Comment by rporres** [comment]
rpn resource does not create anything, apparently it just imports what's there

**Comment by rporres** [comment]
PR: https://github.com/src-d/terraform-provider-online-net/pull/24
